### ISSUE TITLE
Generating wrong sql code

### ISSUE THREAD

**Issue by pedrommone** [jedrzej/pimpable#3] opened 2015-11-05 18:49 UTC
I got the following SQL:

```SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sort' in 'where clause' (SQL: select * from `clients` where `clients`.`deleted_at` is null and `sort` in (created_at, desc) order by `created_at` desc)```

When using `return $this->model->pimp()->get();` on my ClientRepository, also I'm using the following url `api/clients?sort=created_at,desc`

**Comment by jedrzej** [comment] 2015-11-06 10:22
I'm trying to reproduce that but so far no luck. Did you customize the package in any way, like changing default names of sortable fields? Or did you just add "use Pimpable" to your model?

**Comment by pedrommone** [comment] 2015-11-06 11:20
Using version ´"jedrzej/pimpable": "^0.0.3"´´, also, just added use Pimpable and and pimp() behide some queries.

**Comment by jedrzej** [comment] 2015-11-06 11:26
Could you check what version of "jedrzej/searchable" are you using? It's one of the dependencies, maybe you have some older version. If it's not 0.0.7, run composer update

**Comment by pedrommone** [comment] 2015-11-06 11:30
Well, since Im using the pimpable package..

``  "require": {
    "jedrzej/sortable": "0.0.*",
    "jedrzej/searchable": "0.0.*",
    "jedrzej/withable": "0.0.*"
  },``

That shoud get the latest version, right? Also, I've ran ``composer update`` and everthing is updated.

**Comment by jedrzej** [comment] 2015-11-06 11:34
Could you execute "dd(Input::all());" before the return statement and paste the result? As I said, I'm not able to reproduce this issue, I added the trait to one of my models, put the same parameters in the URL and the generated query is ok, so maybe there are some more parameters in the input.

**Comment by pedrommone** [comment] 2015-11-06 11:35
Nop.

`````
array:1 [
  "sort" => "created_at,asc"
]
````

**Comment by pedrommone** [comment] 2015-11-06 11:44
Let me show my code is made.

### Client ###
```php
class Client extends Model
{
    use SoftDeletes;
    use PimpableTrait;

    protected $table = 'clients';
}
```

### AbstractEloquentRepository.php ###
```php
abstract class AbstractEloquentRepository
{
    /**
    * Return all results
    *
    * @return Illuminate\Database\Eloquent\Collection
    */
    public function allPimped()
    {
        return $this->model->pimp()->get();
    }
}
```

### EloquentClientRepository.php ###
```php
class EloquentClientRepository extends AbstractEloquentRepository implements ClientRepository
{
    protected $model;

    public function __construct(Client $model)
    {
        $this->model = $model;
    }
}
```

### ClientRepository.php ###
```php
interface ClientRepository
{
    
}
```

### ClientController.php ##
```php
class ClientController extends Controller
{
    use Helpers;

    protected $repository;

    public function __construct(EloquentClientRepository $repository)
    {
        $this->repository = $repository;
    }

    public function getClients()
    {
        return $this->response->collection(
            $this->repository->allPimped(),
            new ClientsTransformer()
        );
    }
}
```

And the error given

```sql,
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sort' in 'where clause' (SQL: select * from `clients` where `clients`.`deleted_at` is null and `sort` in (created_at, desc) order by `created_at` desc)
```

**Comment by jedrzej** [comment] 2015-11-06 11:50
Thanks for the code, I'll try it out locally later today.

In the meantime... Query that is passed to searchable package is built (incorrectly in your case) in PimpableTrait::scopePimp().
There is a line
````
$query = $query ?: array_except(Input::all(), [$this->sortParameterName, $this->withParameterName]);
````
Could you add
````
dd(Input::all(), $query, $this->sortParameterName);
````
after that and paste the output?

**Comment by pedrommone** [comment] 2015-11-06 11:57
Here we go

```php
array:1 [
  "sort" => array:1 [
    0 => "created_at,desc"
  ]
]
[]
"sort"
```

**Comment by jedrzej** [comment] 2015-11-06 12:06
Thanks, I think I know what's going on, I'll fix it this week.
The reason it didn't work for you but worked for me is that I have defined list of searchable fields for my models, and you don't, so all fields are searchable in your case.
As a workaround, till the issue is fixed, you should define a list of searchable fields in your model and it will solve the issue - you can see example here: https://github.com/jedrzej/searchable#setting-up-searchable-models

**Comment by pedrommone** [comment] 2015-11-06 12:15
First, we made a little mess here.

The issue is with sortable package - this is why I made the pull request, totally mess, haha -, Now I'm using only the sortable trait and worked well.

Thanks a lot for your help. :+1:

**Comment by inov** [comment] 2015-11-10 15:21
I have the same problem with the query:

<pre>
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sort' in 'where clause' (SQL: select * from `clients` where `clients`.`deleted_at` is null and `sort` in (created_at, desc) order by `created_at` desc)</pre>

Is this issue still open, because I saw that the pull request has been merged?

It is not possible to use:

<pre>
public $searchable = ["*"];
</pre>

on the models.

**Comment by jedrzej** [comment] 2015-11-10 17:00
@inov the issue is still open. It's not trivial to fix, as the fix might not be backwards compatible.
As a workaround, till the issue is fixed, please explicitly list the searchable columns in $searchable attribute.

**Comment by inov** [comment] 2015-11-11 07:56
Ok. thank you for the answer. With the workaround the package is working perfectly. With the fix it would be more dynamically implementable for me, so hope you will be able to fix it sometime. Thanks.

**Comment by jedrzej** [comment] 2015-12-21 20:51
Hey @inov @pedrommone,
I've just pushed new version of searchable bundle that excludes parameters used by related sortable/withable packages from the query. It should solve the issues you had.
Cheers
jedrzej

**Closed by jedrzej** 2015-12-21 20:51 UTC
